name: "Rancher Namespace Mover"
author: "kitabisa"
description: |-
  This action will create new project in Rancher cluster and move a given namespace to newly created project.
  If project name is already exist, no new project will be created and the namespace will be move to the existing project.

inputs:
  rancher-host:
    description: |-
      Rancher host URL.
    required: true
  rancher-access-key:
    description: |-
      Rancher access key.
    required: true
  rancher-secret-key:
    description: |-
      Rancher secret key.
    required: true
  cluster-id:
    description: |-
      Cluster ID for any certain rancher environment.
    required: true
  project-name:
    description: |-
      Rancher project name.
    required: true
  namespace:
    description: |-
      Kubernetes namespace.
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
