name: "Setup Helmfile"
author: "kitabisa"
description: |-
  Downloads, installs, and configures a Helmfile for the worker.
  This will add the `helmfile` CLI command to the worker's $PATH.

inputs:
  version:
    description: |-
      Version of the Helmfile to install. If unspecified, the default version will be installed.
    default: "v0.125.9"
    required: false
  additional-helm-plugins:
    description: |-
      A comma separated list of additional helm plugins to install. Should be a valid argument after `helm plugin install`.
    required: false

runs:
  using: "node12"
  main: "setup-helmfile/dist/index.js"
