name: "Setup Helmfile"
author: "kitabisa"
description: |-
  Downloads, installs, and configures a Helmfile for the worker.
  This will add the `helmfile` CLI command to the worker's $PATH.

inputs:
  version:
    description: "Version of the Helmfile to install. If unspecified, the latest version will be installed."
    default: "latest"
    required: false
  sops-version:
    description: "Version of the SOPS to install. If unspecified, the latest version will be installed."
    default: "latest"
    required: false
  helm-diff-version:
    description: "Version of the helm-diff to install. If unspecified, the latest version will be installed."
    default: "latest"
    required: false
  helm-secrets-version:
    description: "Version of the helm-secrets to install. If unspecified, the lates version will be installed."
    default: "latest"
    required: false
  helm-plugins:
    description: "A comma separated list of helm plugins to install. Should be a valid argument after `helm plugin install`."
    default: >
      https://github.com/databus23/helm-diff,
      https://github.com/jkroepke/helm-secrets
    required: false

outputs:
  exit-code:
    description: "Exit code of helmfile. Useful to handle diff --detailed-exitcode"

runs:
  using: "node20"
  main: "dist/index.js"
